#global log level
logLevel=INFO
#comma separated list of packages where to find skeletons
skeletons.path=org.ifolks.generator.skeletons.jsf, org.ifolks.generator.skeletons.rest, org.ifolks.generator.skeletons.angular
#comma separated list of packages where to find database handlers
database.handlers.path=org.ifolks.generator.skeletons.core.database